/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'leo' at '10/02/15 15.47' with Gradle 2.1
 *
 * @author leo, @date 10/02/15 15.47
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
