/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'leo' at '10/02/15 15.47' with Gradle 2.1
 *
 * @author leo, @date 10/02/15 15.47
 */

import spock.lang.Specification

class GroovyProcesserTest extends Specification{
    def "someTest"() {
        setup:
        //FIXME: write tests!!!!
        null

        when:
        //FIXME: write tests!!!!
        null

        then:
        //FIXME: write tests!!!!
        true==true
    }
}
